// <auto-generated />
namespace PowerLog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initializ : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initializ));
        
        string IMigrationMetadata.Id
        {
            get { return "201210250144219_initializ"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
