// <auto-generated />
namespace PowerLog.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class add_comment_to_trainingsession : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_comment_to_trainingsession));
        
        string IMigrationMetadata.Id
        {
            get { return "201210241540247_add_comment_to_trainingsession"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
