//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 3.4
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// $ANTLR 3.4 C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g 2012-10-13 00:19:23

// The variable 'variable' is assigned but its value is never used.
#pragma warning disable 219
// Unreachable code detected.
#pragma warning disable 162
// Missing XML comment for publicly visible type or member 'Type_or_Member'
#pragma warning disable 1591
// CLS compliance checking will not be performed on 'type' because it is not visible from outside this assembly.
#pragma warning disable 3019


//package kebab.bacon;


using System.Collections.Generic;
using Antlr.Runtime;
using Antlr.Runtime.Misc;


using Antlr.Runtime.Tree;
using RewriteRuleITokenStream = Antlr.Runtime.Tree.RewriteRuleTokenStream;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "3.4")]
[System.CLSCompliant(false)]
public partial class PowerLogGrammarParser : Antlr.Runtime.Parser
{
	internal static readonly string[] tokenNames = new string[] {
		"<invalid>", "<EOR>", "<DOWN>", "<UP>", "DATA", "EXERCISE", "EXERCISE_NAME", "FLAGGED_SET", "FLAGS", "FLOAT", "FORCED", "FR", "FTL", "LETTER", "MAX", "MESSAGE", "MULTI_SET", "NOTE", "NUMBER", "REP", "RESULT", "SET", "SETS", "SINGLE", "TF", "WEIGHT", "WORD", "WS", "X", "'('", "')'", "'-'", "';'"
	};
	public const int EOF=-1;
	public const int T__29=29;
	public const int T__30=30;
	public const int T__31=31;
	public const int T__32=32;
	public const int DATA=4;
	public const int EXERCISE=5;
	public const int EXERCISE_NAME=6;
	public const int FLAGGED_SET=7;
	public const int FLAGS=8;
	public const int FLOAT=9;
	public const int FORCED=10;
	public const int FR=11;
	public const int FTL=12;
	public const int LETTER=13;
	public const int MAX=14;
	public const int MESSAGE=15;
	public const int MULTI_SET=16;
	public const int NOTE=17;
	public const int NUMBER=18;
	public const int REP=19;
	public const int RESULT=20;
	public const int SET=21;
	public const int SETS=22;
	public const int SINGLE=23;
	public const int TF=24;
	public const int WEIGHT=25;
	public const int WORD=26;
	public const int WS=27;
	public const int X=28;

	public PowerLogGrammarParser(ITokenStream input)
		: this(input, new RecognizerSharedState())
	{
	}
	public PowerLogGrammarParser(ITokenStream input, RecognizerSharedState state)
		: base(input, state)
	{
		ITreeAdaptor treeAdaptor = default(ITreeAdaptor);
		CreateTreeAdaptor(ref treeAdaptor);
		TreeAdaptor = treeAdaptor ?? new CommonTreeAdaptor();
		OnCreated();
	}
	// Implement this function in your helper file to use a custom tree adaptor
	partial void CreateTreeAdaptor(ref ITreeAdaptor adaptor);

	private ITreeAdaptor adaptor;

	public ITreeAdaptor TreeAdaptor
	{
		get
		{
			return adaptor;
		}

		set
		{
			this.adaptor = value;
		}
	}

	public override string[] TokenNames { get { return PowerLogGrammarParser.tokenNames; } }
	public override string GrammarFileName { get { return "C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g"; } }


	partial void OnCreated();
	partial void EnterRule(string ruleName, int ruleIndex);
	partial void LeaveRule(string ruleName, int ruleIndex);

	#region Rules
	partial void EnterRule_evaluate();
	partial void LeaveRule_evaluate();

	// $ANTLR start "evaluate"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:43:8: public evaluate : exercise ( ';' exercise )* EOF -> ^( 'result' ( exercise )+ ) ;
	[GrammarRule("evaluate")]
	public AstParserRuleReturnScope<CommonTree, CommonToken> evaluate()
	{
		EnterRule_evaluate();
		EnterRule("evaluate", 1);
		TraceIn("evaluate", 1);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken char_literal2 = default(CommonToken);
		CommonToken EOF4 = default(CommonToken);
		AstParserRuleReturnScope<CommonTree, CommonToken> exercise1 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> exercise3 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);

		CommonTree char_literal2_tree = default(CommonTree);
		CommonTree EOF4_tree = default(CommonTree);
		RewriteRuleITokenStream stream_32=new RewriteRuleITokenStream(adaptor,"token 32");
		RewriteRuleITokenStream stream_EOF=new RewriteRuleITokenStream(adaptor,"token EOF");
		RewriteRuleSubtreeStream stream_exercise=new RewriteRuleSubtreeStream(adaptor,"rule exercise");
		try { DebugEnterRule(GrammarFileName, "evaluate");
		DebugLocation(43, 6);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:44:7: ( exercise ( ';' exercise )* EOF -> ^( 'result' ( exercise )+ ) )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:44:11: exercise ( ';' exercise )* EOF
			{
			DebugLocation(44, 11);
			PushFollow(Follow._exercise_in_evaluate196);
			exercise1=exercise();
			PopFollow();

			stream_exercise.Add(exercise1.Tree);
			DebugLocation(44, 20);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:44:20: ( ';' exercise )*
			try { DebugEnterSubRule(1);
			while (true)
			{
				int alt1=2;
				try { DebugEnterDecision(1, false);
				int LA1_0 = input.LA(1);

				if ((LA1_0==32))
				{
					alt1 = 1;
				}


				} finally { DebugExitDecision(1); }
				switch ( alt1 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:44:21: ';' exercise
					{
					DebugLocation(44, 21);
					char_literal2=(CommonToken)Match(input,32,Follow._32_in_evaluate199);  
					stream_32.Add(char_literal2);

					DebugLocation(44, 25);
					PushFollow(Follow._exercise_in_evaluate201);
					exercise3=exercise();
					PopFollow();

					stream_exercise.Add(exercise3.Tree);

					}
					break;

				default:
					goto loop1;
				}
			}

			loop1:
				;

			} finally { DebugExitSubRule(1); }

			DebugLocation(44, 36);
			EOF4=(CommonToken)Match(input,EOF,Follow._EOF_in_evaluate205);  
			stream_EOF.Add(EOF4);



			{
			// AST REWRITE
			// elements: exercise, RESULT
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (CommonTree)adaptor.Nil();
			// 44:41: -> ^( 'result' ( exercise )+ )
			{
				DebugLocation(44, 45);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:44:45: ^( 'result' ( exercise )+ )
				{
				CommonTree root_1 = (CommonTree)adaptor.Nil();
				DebugLocation(44, 47);
				root_1 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(RESULT, "RESULT"), root_1);

				DebugLocation(44, 56);
				if (!(stream_exercise.HasNext))
				{
					throw new RewriteEarlyExitException();
				}
				while ( stream_exercise.HasNext )
				{
					DebugLocation(44, 56);
					adaptor.AddChild(root_1, stream_exercise.NextTree());

				}
				stream_exercise.Reset();

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("evaluate", 1);
			LeaveRule("evaluate", 1);
			LeaveRule_evaluate();
		}
		DebugLocation(45, 6);
		} finally { DebugExitRule(GrammarFileName, "evaluate"); }
		return retval;

	}
	// $ANTLR end "evaluate"

	partial void EnterRule_annotatedSet();
	partial void LeaveRule_annotatedSet();

	// $ANTLR start "annotatedSet"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:47:1: annotatedSet : set ( forced | note | flag )* -> ^( 'flagged_set' set ^( 'flags' ( flag )* ( forced )? ( note )? ) ) ;
	[GrammarRule("annotatedSet")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> annotatedSet()
	{
		EnterRule_annotatedSet();
		EnterRule("annotatedSet", 2);
		TraceIn("annotatedSet", 2);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		AstParserRuleReturnScope<CommonTree, CommonToken> set5 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> forced6 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> note7 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> flag8 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);

		RewriteRuleSubtreeStream stream_flag=new RewriteRuleSubtreeStream(adaptor,"rule flag");
		RewriteRuleSubtreeStream stream_set=new RewriteRuleSubtreeStream(adaptor,"rule set");
		RewriteRuleSubtreeStream stream_note=new RewriteRuleSubtreeStream(adaptor,"rule note");
		RewriteRuleSubtreeStream stream_forced=new RewriteRuleSubtreeStream(adaptor,"rule forced");
		try { DebugEnterRule(GrammarFileName, "annotatedSet");
		DebugLocation(47, 6);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:7: ( set ( forced | note | flag )* -> ^( 'flagged_set' set ^( 'flags' ( flag )* ( forced )? ( note )? ) ) )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:11: set ( forced | note | flag )*
			{
			DebugLocation(48, 11);
			PushFollow(Follow._set_in_annotatedSet239);
			set5=set();
			PopFollow();

			stream_set.Add(set5.Tree);
			DebugLocation(48, 15);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:15: ( forced | note | flag )*
			try { DebugEnterSubRule(2);
			while (true)
			{
				int alt2=4;
				try { DebugEnterDecision(2, false);
				int LA2_0 = input.LA(1);

				if ((LA2_0==31))
				{
					switch (input.LA(2))
					{
					case FR:
						{
						alt2 = 1;
						}
						break;
					case NOTE:
						{
						alt2 = 2;
						}
						break;
					case FTL:
					case MAX:
					case TF:
						{
						alt2 = 3;
						}
						break;
					}

				}


				} finally { DebugExitDecision(2); }
				switch ( alt2 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:16: forced
					{
					DebugLocation(48, 16);
					PushFollow(Follow._forced_in_annotatedSet242);
					forced6=forced();
					PopFollow();

					stream_forced.Add(forced6.Tree);

					}
					break;
				case 2:
					DebugEnterAlt(2);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:23: note
					{
					DebugLocation(48, 23);
					PushFollow(Follow._note_in_annotatedSet244);
					note7=note();
					PopFollow();

					stream_note.Add(note7.Tree);

					}
					break;
				case 3:
					DebugEnterAlt(3);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:28: flag
					{
					DebugLocation(48, 28);
					PushFollow(Follow._flag_in_annotatedSet246);
					flag8=flag();
					PopFollow();

					stream_flag.Add(flag8.Tree);

					}
					break;

				default:
					goto loop2;
				}
			}

			loop2:
				;

			} finally { DebugExitSubRule(2); }



			{
			// AST REWRITE
			// elements: set, forced, FLAGGED_SET, flag, FLAGS, note
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (CommonTree)adaptor.Nil();
			// 48:41: -> ^( 'flagged_set' set ^( 'flags' ( flag )* ( forced )? ( note )? ) )
			{
				DebugLocation(48, 45);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:45: ^( 'flagged_set' set ^( 'flags' ( flag )* ( forced )? ( note )? ) )
				{
				CommonTree root_1 = (CommonTree)adaptor.Nil();
				DebugLocation(48, 47);
				root_1 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(FLAGGED_SET, "FLAGGED_SET"), root_1);

				DebugLocation(48, 61);
				adaptor.AddChild(root_1, stream_set.NextTree());
				DebugLocation(48, 65);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:65: ^( 'flags' ( flag )* ( forced )? ( note )? )
				{
				CommonTree root_2 = (CommonTree)adaptor.Nil();
				DebugLocation(48, 67);
				root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(FLAGS, "FLAGS"), root_2);

				DebugLocation(48, 75);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:75: ( flag )*
				while ( stream_flag.HasNext )
				{
					DebugLocation(48, 75);
					adaptor.AddChild(root_2, stream_flag.NextTree());

				}
				stream_flag.Reset();
				DebugLocation(48, 81);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:81: ( forced )?
				if (stream_forced.HasNext)
				{
					DebugLocation(48, 81);
					adaptor.AddChild(root_2, stream_forced.NextTree());

				}
				stream_forced.Reset();
				DebugLocation(48, 89);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:48:89: ( note )?
				if (stream_note.HasNext)
				{
					DebugLocation(48, 89);
					adaptor.AddChild(root_2, stream_note.NextTree());

				}
				stream_note.Reset();

				adaptor.AddChild(root_1, root_2);
				}

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("annotatedSet", 2);
			LeaveRule("annotatedSet", 2);
			LeaveRule_annotatedSet();
		}
		DebugLocation(49, 6);
		} finally { DebugExitRule(GrammarFileName, "annotatedSet"); }
		return retval;

	}
	// $ANTLR end "annotatedSet"

	partial void EnterRule_set();
	partial void LeaveRule_set();

	// $ANTLR start "set"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:51:1: set : ( sets X reps X weight -> ^( 'multi_set' ^( 'sets' sets ) ^( 'rep' reps ) ^( 'weight' weight ) ) | reps X weight -> ^( 'set' ^( 'rep' reps ) ^( 'weight' weight ) ) | weight -> ^( 'set' ^( 'rep' 'single' ) ^( 'weight' weight ) ) );
	[GrammarRule("set")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> set()
	{
		EnterRule_set();
		EnterRule("set", 3);
		TraceIn("set", 3);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken X10 = default(CommonToken);
		CommonToken X12 = default(CommonToken);
		CommonToken X15 = default(CommonToken);
		AstParserRuleReturnScope<CommonTree, CommonToken> sets9 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> reps11 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> weight13 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> reps14 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> weight16 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> weight17 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);

		CommonTree X10_tree = default(CommonTree);
		CommonTree X12_tree = default(CommonTree);
		CommonTree X15_tree = default(CommonTree);
		RewriteRuleITokenStream stream_X=new RewriteRuleITokenStream(adaptor,"token X");
		RewriteRuleSubtreeStream stream_reps=new RewriteRuleSubtreeStream(adaptor,"rule reps");
		RewriteRuleSubtreeStream stream_weight=new RewriteRuleSubtreeStream(adaptor,"rule weight");
		RewriteRuleSubtreeStream stream_sets=new RewriteRuleSubtreeStream(adaptor,"rule sets");
		try { DebugEnterRule(GrammarFileName, "set");
		DebugLocation(51, 6);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:52:7: ( sets X reps X weight -> ^( 'multi_set' ^( 'sets' sets ) ^( 'rep' reps ) ^( 'weight' weight ) ) | reps X weight -> ^( 'set' ^( 'rep' reps ) ^( 'weight' weight ) ) | weight -> ^( 'set' ^( 'rep' 'single' ) ^( 'weight' weight ) ) )
			int alt3=3;
			try { DebugEnterDecision(3, false);
			int LA3_0 = input.LA(1);

			if ((LA3_0==NUMBER))
			{
				int LA3_1 = input.LA(2);

				if ((LA3_1==X))
				{
					int LA3_3 = input.LA(3);

					if ((LA3_3==NUMBER))
					{
						int LA3_4 = input.LA(4);

						if ((LA3_4==X))
						{
							alt3 = 1;
						}
						else if ((LA3_4==EOF||LA3_4==WS||(LA3_4>=31 && LA3_4<=32)))
						{
							alt3 = 2;
						}
						else
						{
							NoViableAltException nvae = new NoViableAltException("", 3, 4, input);
							DebugRecognitionException(nvae);
							throw nvae;
						}
					}
					else if ((LA3_3==FLOAT))
					{
						alt3 = 2;
					}
					else
					{
						NoViableAltException nvae = new NoViableAltException("", 3, 3, input);
						DebugRecognitionException(nvae);
						throw nvae;
					}
				}
				else if ((LA3_1==EOF||LA3_1==WS||(LA3_1>=31 && LA3_1<=32)))
				{
					alt3 = 3;
				}
				else
				{
					NoViableAltException nvae = new NoViableAltException("", 3, 1, input);
					DebugRecognitionException(nvae);
					throw nvae;
				}
			}
			else if ((LA3_0==FLOAT))
			{
				alt3 = 3;
			}
			else
			{
				NoViableAltException nvae = new NoViableAltException("", 3, 0, input);
				DebugRecognitionException(nvae);
				throw nvae;
			}
			} finally { DebugExitDecision(3); }
			switch (alt3)
			{
			case 1:
				DebugEnterAlt(1);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:52:11: sets X reps X weight
				{
				DebugLocation(52, 11);
				PushFollow(Follow._sets_in_set307);
				sets9=sets();
				PopFollow();

				stream_sets.Add(sets9.Tree);
				DebugLocation(52, 16);
				X10=(CommonToken)Match(input,X,Follow._X_in_set309);  
				stream_X.Add(X10);

				DebugLocation(52, 18);
				PushFollow(Follow._reps_in_set311);
				reps11=reps();
				PopFollow();

				stream_reps.Add(reps11.Tree);
				DebugLocation(52, 23);
				X12=(CommonToken)Match(input,X,Follow._X_in_set313);  
				stream_X.Add(X12);

				DebugLocation(52, 25);
				PushFollow(Follow._weight_in_set315);
				weight13=weight();
				PopFollow();

				stream_weight.Add(weight13.Tree);


				{
				// AST REWRITE
				// elements: WEIGHT, weight, MULTI_SET, REP, SETS, reps, sets
				// token labels: 
				// rule labels: retval
				// token list labels: 
				// rule list labels: 
				// wildcard labels: 
				retval.Tree = root_0;
				RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

				root_0 = (CommonTree)adaptor.Nil();
				// 52:41: -> ^( 'multi_set' ^( 'sets' sets ) ^( 'rep' reps ) ^( 'weight' weight ) )
				{
					DebugLocation(52, 45);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:52:45: ^( 'multi_set' ^( 'sets' sets ) ^( 'rep' reps ) ^( 'weight' weight ) )
					{
					CommonTree root_1 = (CommonTree)adaptor.Nil();
					DebugLocation(52, 47);
					root_1 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(MULTI_SET, "MULTI_SET"), root_1);

					DebugLocation(52, 59);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:52:59: ^( 'sets' sets )
					{
					CommonTree root_2 = (CommonTree)adaptor.Nil();
					DebugLocation(52, 61);
					root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(SETS, "SETS"), root_2);

					DebugLocation(52, 68);
					adaptor.AddChild(root_2, stream_sets.NextTree());

					adaptor.AddChild(root_1, root_2);
					}
					DebugLocation(52, 74);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:52:74: ^( 'rep' reps )
					{
					CommonTree root_2 = (CommonTree)adaptor.Nil();
					DebugLocation(52, 76);
					root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(REP, "REP"), root_2);

					DebugLocation(52, 82);
					adaptor.AddChild(root_2, stream_reps.NextTree());

					adaptor.AddChild(root_1, root_2);
					}
					DebugLocation(52, 88);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:52:88: ^( 'weight' weight )
					{
					CommonTree root_2 = (CommonTree)adaptor.Nil();
					DebugLocation(52, 90);
					root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(WEIGHT, "WEIGHT"), root_2);

					DebugLocation(52, 99);
					adaptor.AddChild(root_2, stream_weight.NextTree());

					adaptor.AddChild(root_1, root_2);
					}

					adaptor.AddChild(root_0, root_1);
					}

				}

				retval.Tree = root_0;
				}

				}
				break;
			case 2:
				DebugEnterAlt(2);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:53:11: reps X weight
				{
				DebugLocation(53, 11);
				PushFollow(Follow._reps_in_set361);
				reps14=reps();
				PopFollow();

				stream_reps.Add(reps14.Tree);
				DebugLocation(53, 16);
				X15=(CommonToken)Match(input,X,Follow._X_in_set363);  
				stream_X.Add(X15);

				DebugLocation(53, 18);
				PushFollow(Follow._weight_in_set365);
				weight16=weight();
				PopFollow();

				stream_weight.Add(weight16.Tree);


				{
				// AST REWRITE
				// elements: WEIGHT, SET, weight, reps, REP
				// token labels: 
				// rule labels: retval
				// token list labels: 
				// rule list labels: 
				// wildcard labels: 
				retval.Tree = root_0;
				RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

				root_0 = (CommonTree)adaptor.Nil();
				// 53:41: -> ^( 'set' ^( 'rep' reps ) ^( 'weight' weight ) )
				{
					DebugLocation(53, 45);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:53:45: ^( 'set' ^( 'rep' reps ) ^( 'weight' weight ) )
					{
					CommonTree root_1 = (CommonTree)adaptor.Nil();
					DebugLocation(53, 47);
					root_1 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(SET, "SET"), root_1);

					DebugLocation(53, 53);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:53:53: ^( 'rep' reps )
					{
					CommonTree root_2 = (CommonTree)adaptor.Nil();
					DebugLocation(53, 55);
					root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(REP, "REP"), root_2);

					DebugLocation(53, 61);
					adaptor.AddChild(root_2, stream_reps.NextTree());

					adaptor.AddChild(root_1, root_2);
					}
					DebugLocation(53, 67);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:53:67: ^( 'weight' weight )
					{
					CommonTree root_2 = (CommonTree)adaptor.Nil();
					DebugLocation(53, 69);
					root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(WEIGHT, "WEIGHT"), root_2);

					DebugLocation(53, 78);
					adaptor.AddChild(root_2, stream_weight.NextTree());

					adaptor.AddChild(root_1, root_2);
					}

					adaptor.AddChild(root_0, root_1);
					}

				}

				retval.Tree = root_0;
				}

				}
				break;
			case 3:
				DebugEnterAlt(3);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:54:11: weight
				{
				DebugLocation(54, 11);
				PushFollow(Follow._weight_in_set412);
				weight17=weight();
				PopFollow();

				stream_weight.Add(weight17.Tree);


				{
				// AST REWRITE
				// elements: REP, weight, SET, WEIGHT, SINGLE
				// token labels: 
				// rule labels: retval
				// token list labels: 
				// rule list labels: 
				// wildcard labels: 
				retval.Tree = root_0;
				RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

				root_0 = (CommonTree)adaptor.Nil();
				// 54:41: -> ^( 'set' ^( 'rep' 'single' ) ^( 'weight' weight ) )
				{
					DebugLocation(54, 45);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:54:45: ^( 'set' ^( 'rep' 'single' ) ^( 'weight' weight ) )
					{
					CommonTree root_1 = (CommonTree)adaptor.Nil();
					DebugLocation(54, 47);
					root_1 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(SET, "SET"), root_1);

					DebugLocation(54, 53);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:54:53: ^( 'rep' 'single' )
					{
					CommonTree root_2 = (CommonTree)adaptor.Nil();
					DebugLocation(54, 55);
					root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(REP, "REP"), root_2);

					DebugLocation(54, 61);
					adaptor.AddChild(root_2, (CommonTree)adaptor.Create(SINGLE, "SINGLE"));

					adaptor.AddChild(root_1, root_2);
					}
					DebugLocation(54, 72);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:54:72: ^( 'weight' weight )
					{
					CommonTree root_2 = (CommonTree)adaptor.Nil();
					DebugLocation(54, 74);
					root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(WEIGHT, "WEIGHT"), root_2);

					DebugLocation(54, 83);
					adaptor.AddChild(root_2, stream_weight.NextTree());

					adaptor.AddChild(root_1, root_2);
					}

					adaptor.AddChild(root_0, root_1);
					}

				}

				retval.Tree = root_0;
				}

				}
				break;

			}
			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("set", 3);
			LeaveRule("set", 3);
			LeaveRule_set();
		}
		DebugLocation(55, 6);
		} finally { DebugExitRule(GrammarFileName, "set"); }
		return retval;

	}
	// $ANTLR end "set"

	partial void EnterRule_exercise();
	partial void LeaveRule_exercise();

	// $ANTLR start "exercise"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:57:1: exercise : text ( ( WS )+ annotatedSet )+ -> ^( 'exercise' ^( 'exercise_name' text ) ^( 'data' ( annotatedSet )* ) ) ;
	[GrammarRule("exercise")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> exercise()
	{
		EnterRule_exercise();
		EnterRule("exercise", 4);
		TraceIn("exercise", 4);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken WS19 = default(CommonToken);
		AstParserRuleReturnScope<CommonTree, CommonToken> text18 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);
		AstParserRuleReturnScope<CommonTree, CommonToken> annotatedSet20 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);

		CommonTree WS19_tree = default(CommonTree);
		RewriteRuleITokenStream stream_WS=new RewriteRuleITokenStream(adaptor,"token WS");
		RewriteRuleSubtreeStream stream_text=new RewriteRuleSubtreeStream(adaptor,"rule text");
		RewriteRuleSubtreeStream stream_annotatedSet=new RewriteRuleSubtreeStream(adaptor,"rule annotatedSet");
		try { DebugEnterRule(GrammarFileName, "exercise");
		DebugLocation(57, 6);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:7: ( text ( ( WS )+ annotatedSet )+ -> ^( 'exercise' ^( 'exercise_name' text ) ^( 'data' ( annotatedSet )* ) ) )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:9: text ( ( WS )+ annotatedSet )+
			{
			DebugLocation(58, 9);
			PushFollow(Follow._text_in_exercise477);
			text18=text();
			PopFollow();

			stream_text.Add(text18.Tree);
			DebugLocation(58, 14);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:14: ( ( WS )+ annotatedSet )+
			int cnt5=0;
			try { DebugEnterSubRule(5);
			while (true)
			{
				int alt5=2;
				try { DebugEnterDecision(5, false);
				int LA5_0 = input.LA(1);

				if ((LA5_0==WS))
				{
					alt5 = 1;
				}


				} finally { DebugExitDecision(5); }
				switch (alt5)
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:15: ( WS )+ annotatedSet
					{
					DebugLocation(58, 15);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:15: ( WS )+
					int cnt4=0;
					try { DebugEnterSubRule(4);
					while (true)
					{
						int alt4=2;
						try { DebugEnterDecision(4, false);
						int LA4_0 = input.LA(1);

						if ((LA4_0==WS))
						{
							alt4 = 1;
						}


						} finally { DebugExitDecision(4); }
						switch (alt4)
						{
						case 1:
							DebugEnterAlt(1);
							// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:15: WS
							{
							DebugLocation(58, 15);
							WS19=(CommonToken)Match(input,WS,Follow._WS_in_exercise480);  
							stream_WS.Add(WS19);


							}
							break;

						default:
							if (cnt4 >= 1)
								goto loop4;

							EarlyExitException eee4 = new EarlyExitException( 4, input );
							DebugRecognitionException(eee4);
							throw eee4;
						}
						cnt4++;
					}
					loop4:
						;

					} finally { DebugExitSubRule(4); }

					DebugLocation(58, 19);
					PushFollow(Follow._annotatedSet_in_exercise483);
					annotatedSet20=annotatedSet();
					PopFollow();

					stream_annotatedSet.Add(annotatedSet20.Tree);

					}
					break;

				default:
					if (cnt5 >= 1)
						goto loop5;

					EarlyExitException eee5 = new EarlyExitException( 5, input );
					DebugRecognitionException(eee5);
					throw eee5;
				}
				cnt5++;
			}
			loop5:
				;

			} finally { DebugExitSubRule(5); }



			{
			// AST REWRITE
			// elements: annotatedSet, DATA, text, EXERCISE, EXERCISE_NAME
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (CommonTree)adaptor.Nil();
			// 58:41: -> ^( 'exercise' ^( 'exercise_name' text ) ^( 'data' ( annotatedSet )* ) )
			{
				DebugLocation(58, 45);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:45: ^( 'exercise' ^( 'exercise_name' text ) ^( 'data' ( annotatedSet )* ) )
				{
				CommonTree root_1 = (CommonTree)adaptor.Nil();
				DebugLocation(58, 47);
				root_1 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(EXERCISE, "EXERCISE"), root_1);

				DebugLocation(58, 58);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:58: ^( 'exercise_name' text )
				{
				CommonTree root_2 = (CommonTree)adaptor.Nil();
				DebugLocation(58, 60);
				root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(EXERCISE_NAME, "EXERCISE_NAME"), root_2);

				DebugLocation(58, 76);
				adaptor.AddChild(root_2, stream_text.NextTree());

				adaptor.AddChild(root_1, root_2);
				}
				DebugLocation(58, 82);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:82: ^( 'data' ( annotatedSet )* )
				{
				CommonTree root_2 = (CommonTree)adaptor.Nil();
				DebugLocation(58, 84);
				root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(DATA, "DATA"), root_2);

				DebugLocation(58, 91);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:58:91: ( annotatedSet )*
				while ( stream_annotatedSet.HasNext )
				{
					DebugLocation(58, 91);
					adaptor.AddChild(root_2, stream_annotatedSet.NextTree());

				}
				stream_annotatedSet.Reset();

				adaptor.AddChild(root_1, root_2);
				}

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("exercise", 4);
			LeaveRule("exercise", 4);
			LeaveRule_exercise();
		}
		DebugLocation(59, 6);
		} finally { DebugExitRule(GrammarFileName, "exercise"); }
		return retval;

	}
	// $ANTLR end "exercise"

	partial void EnterRule_flag();
	partial void LeaveRule_flag();

	// $ANTLR start "flag"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:61:1: flag : '-' ! ( MAX | FTL | TF ) ;
	[GrammarRule("flag")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> flag()
	{
		EnterRule_flag();
		EnterRule("flag", 5);
		TraceIn("flag", 5);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken char_literal21 = default(CommonToken);
		CommonToken set22 = default(CommonToken);

		CommonTree char_literal21_tree = default(CommonTree);
		CommonTree set22_tree = default(CommonTree);
		try { DebugEnterRule(GrammarFileName, "flag");
		DebugLocation(61, 6);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:62:7: ( '-' ! ( MAX | FTL | TF ) )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:62:9: '-' ! ( MAX | FTL | TF )
			{
			root_0 = (CommonTree)adaptor.Nil();

			DebugLocation(62, 12);
			char_literal21=(CommonToken)Match(input,31,Follow._31_in_flag540); 
			DebugLocation(62, 14);

			set22=(CommonToken)input.LT(1);
			if (input.LA(1)==FTL||input.LA(1)==MAX||input.LA(1)==TF)
			{
				input.Consume();
				adaptor.AddChild(root_0, (CommonTree)adaptor.Create(set22));
				state.errorRecovery=false;
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				throw mse;
			}


			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("flag", 5);
			LeaveRule("flag", 5);
			LeaveRule_flag();
		}
		DebugLocation(63, 6);
		} finally { DebugExitRule(GrammarFileName, "flag"); }
		return retval;

	}
	// $ANTLR end "flag"

	partial void EnterRule_note();
	partial void LeaveRule_note();

	// $ANTLR start "note"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:65:1: note : '-' NOTE '(' text ')' -> ^( 'note' ^( 'message' text ) ) ;
	[GrammarRule("note")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> note()
	{
		EnterRule_note();
		EnterRule("note", 6);
		TraceIn("note", 6);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken char_literal23 = default(CommonToken);
		CommonToken NOTE24 = default(CommonToken);
		CommonToken char_literal25 = default(CommonToken);
		CommonToken char_literal27 = default(CommonToken);
		AstParserRuleReturnScope<CommonTree, CommonToken> text26 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);

		CommonTree char_literal23_tree = default(CommonTree);
		CommonTree NOTE24_tree = default(CommonTree);
		CommonTree char_literal25_tree = default(CommonTree);
		CommonTree char_literal27_tree = default(CommonTree);
		RewriteRuleITokenStream stream_30=new RewriteRuleITokenStream(adaptor,"token 30");
		RewriteRuleITokenStream stream_31=new RewriteRuleITokenStream(adaptor,"token 31");
		RewriteRuleITokenStream stream_NOTE=new RewriteRuleITokenStream(adaptor,"token NOTE");
		RewriteRuleITokenStream stream_29=new RewriteRuleITokenStream(adaptor,"token 29");
		RewriteRuleSubtreeStream stream_text=new RewriteRuleSubtreeStream(adaptor,"rule text");
		try { DebugEnterRule(GrammarFileName, "note");
		DebugLocation(65, 6);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:66:7: ( '-' NOTE '(' text ')' -> ^( 'note' ^( 'message' text ) ) )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:66:9: '-' NOTE '(' text ')'
			{
			DebugLocation(66, 9);
			char_literal23=(CommonToken)Match(input,31,Follow._31_in_note578);  
			stream_31.Add(char_literal23);

			DebugLocation(66, 13);
			NOTE24=(CommonToken)Match(input,NOTE,Follow._NOTE_in_note580);  
			stream_NOTE.Add(NOTE24);

			DebugLocation(66, 18);
			char_literal25=(CommonToken)Match(input,29,Follow._29_in_note582);  
			stream_29.Add(char_literal25);

			DebugLocation(66, 22);
			PushFollow(Follow._text_in_note584);
			text26=text();
			PopFollow();

			stream_text.Add(text26.Tree);
			DebugLocation(66, 27);
			char_literal27=(CommonToken)Match(input,30,Follow._30_in_note586);  
			stream_30.Add(char_literal27);



			{
			// AST REWRITE
			// elements: MESSAGE, text, NOTE
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (CommonTree)adaptor.Nil();
			// 66:41: -> ^( 'note' ^( 'message' text ) )
			{
				DebugLocation(66, 45);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:66:45: ^( 'note' ^( 'message' text ) )
				{
				CommonTree root_1 = (CommonTree)adaptor.Nil();
				DebugLocation(66, 47);
				root_1 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(NOTE, "NOTE"), root_1);

				DebugLocation(66, 54);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:66:54: ^( 'message' text )
				{
				CommonTree root_2 = (CommonTree)adaptor.Nil();
				DebugLocation(66, 56);
				root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(MESSAGE, "MESSAGE"), root_2);

				DebugLocation(66, 66);
				adaptor.AddChild(root_2, stream_text.NextTree());

				adaptor.AddChild(root_1, root_2);
				}

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("note", 6);
			LeaveRule("note", 6);
			LeaveRule_note();
		}
		DebugLocation(67, 6);
		} finally { DebugExitRule(GrammarFileName, "note"); }
		return retval;

	}
	// $ANTLR end "note"

	partial void EnterRule_forced();
	partial void LeaveRule_forced();

	// $ANTLR start "forced"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:69:1: forced : '-' FR '(' reps ')' -> ^( 'forced' ^( 'rep' reps ) ) ;
	[GrammarRule("forced")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> forced()
	{
		EnterRule_forced();
		EnterRule("forced", 7);
		TraceIn("forced", 7);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken char_literal28 = default(CommonToken);
		CommonToken FR29 = default(CommonToken);
		CommonToken char_literal30 = default(CommonToken);
		CommonToken char_literal32 = default(CommonToken);
		AstParserRuleReturnScope<CommonTree, CommonToken> reps31 = default(AstParserRuleReturnScope<CommonTree, CommonToken>);

		CommonTree char_literal28_tree = default(CommonTree);
		CommonTree FR29_tree = default(CommonTree);
		CommonTree char_literal30_tree = default(CommonTree);
		CommonTree char_literal32_tree = default(CommonTree);
		RewriteRuleITokenStream stream_FR=new RewriteRuleITokenStream(adaptor,"token FR");
		RewriteRuleITokenStream stream_30=new RewriteRuleITokenStream(adaptor,"token 30");
		RewriteRuleITokenStream stream_31=new RewriteRuleITokenStream(adaptor,"token 31");
		RewriteRuleITokenStream stream_29=new RewriteRuleITokenStream(adaptor,"token 29");
		RewriteRuleSubtreeStream stream_reps=new RewriteRuleSubtreeStream(adaptor,"rule reps");
		try { DebugEnterRule(GrammarFileName, "forced");
		DebugLocation(69, 6);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:70:7: ( '-' FR '(' reps ')' -> ^( 'forced' ^( 'rep' reps ) ) )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:70:9: '-' FR '(' reps ')'
			{
			DebugLocation(70, 9);
			char_literal28=(CommonToken)Match(input,31,Follow._31_in_forced639);  
			stream_31.Add(char_literal28);

			DebugLocation(70, 13);
			FR29=(CommonToken)Match(input,FR,Follow._FR_in_forced641);  
			stream_FR.Add(FR29);

			DebugLocation(70, 16);
			char_literal30=(CommonToken)Match(input,29,Follow._29_in_forced643);  
			stream_29.Add(char_literal30);

			DebugLocation(70, 20);
			PushFollow(Follow._reps_in_forced645);
			reps31=reps();
			PopFollow();

			stream_reps.Add(reps31.Tree);
			DebugLocation(70, 25);
			char_literal32=(CommonToken)Match(input,30,Follow._30_in_forced647);  
			stream_30.Add(char_literal32);



			{
			// AST REWRITE
			// elements: REP, FORCED, reps
			// token labels: 
			// rule labels: retval
			// token list labels: 
			// rule list labels: 
			// wildcard labels: 
			retval.Tree = root_0;
			RewriteRuleSubtreeStream stream_retval=new RewriteRuleSubtreeStream(adaptor,"rule retval",retval!=null?retval.Tree:null);

			root_0 = (CommonTree)adaptor.Nil();
			// 70:41: -> ^( 'forced' ^( 'rep' reps ) )
			{
				DebugLocation(70, 45);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:70:45: ^( 'forced' ^( 'rep' reps ) )
				{
				CommonTree root_1 = (CommonTree)adaptor.Nil();
				DebugLocation(70, 47);
				root_1 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(FORCED, "FORCED"), root_1);

				DebugLocation(70, 56);
				// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:70:56: ^( 'rep' reps )
				{
				CommonTree root_2 = (CommonTree)adaptor.Nil();
				DebugLocation(70, 58);
				root_2 = (CommonTree)adaptor.BecomeRoot((CommonTree)adaptor.Create(REP, "REP"), root_2);

				DebugLocation(70, 64);
				adaptor.AddChild(root_2, stream_reps.NextTree());

				adaptor.AddChild(root_1, root_2);
				}

				adaptor.AddChild(root_0, root_1);
				}

			}

			retval.Tree = root_0;
			}

			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("forced", 7);
			LeaveRule("forced", 7);
			LeaveRule_forced();
		}
		DebugLocation(71, 6);
		} finally { DebugExitRule(GrammarFileName, "forced"); }
		return retval;

	}
	// $ANTLR end "forced"

	partial void EnterRule_text();
	partial void LeaveRule_text();

	// $ANTLR start "text"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:73:1: text : WORD ( ( WS !)+ WORD )* ;
	[GrammarRule("text")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> text()
	{
		EnterRule_text();
		EnterRule("text", 8);
		TraceIn("text", 8);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken WORD33 = default(CommonToken);
		CommonToken WS34 = default(CommonToken);
		CommonToken WORD35 = default(CommonToken);

		CommonTree WORD33_tree = default(CommonTree);
		CommonTree WS34_tree = default(CommonTree);
		CommonTree WORD35_tree = default(CommonTree);
		try { DebugEnterRule(GrammarFileName, "text");
		DebugLocation(73, 6);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:74:7: ( WORD ( ( WS !)+ WORD )* )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:74:9: WORD ( ( WS !)+ WORD )*
			{
			root_0 = (CommonTree)adaptor.Nil();

			DebugLocation(74, 9);
			WORD33=(CommonToken)Match(input,WORD,Follow._WORD_in_text702); 
			WORD33_tree = (CommonTree)adaptor.Create(WORD33);
			adaptor.AddChild(root_0, WORD33_tree);
			DebugLocation(74, 14);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:74:14: ( ( WS !)+ WORD )*
			try { DebugEnterSubRule(7);
			while (true)
			{
				int alt7=2;
				try { DebugEnterDecision(7, false);
				try
				{
					alt7 = dfa7.Predict(input);
				}
				catch (NoViableAltException nvae)
				{
					DebugRecognitionException(nvae);
					throw;
				}
				} finally { DebugExitDecision(7); }
				switch ( alt7 )
				{
				case 1:
					DebugEnterAlt(1);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:74:15: ( WS !)+ WORD
					{
					DebugLocation(74, 17);
					// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:74:17: ( WS !)+
					int cnt6=0;
					try { DebugEnterSubRule(6);
					while (true)
					{
						int alt6=2;
						try { DebugEnterDecision(6, false);
						int LA6_0 = input.LA(1);

						if ((LA6_0==WS))
						{
							alt6 = 1;
						}


						} finally { DebugExitDecision(6); }
						switch (alt6)
						{
						case 1:
							DebugEnterAlt(1);
							// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:74:17: WS !
							{
							DebugLocation(74, 17);
							WS34=(CommonToken)Match(input,WS,Follow._WS_in_text705); 

							}
							break;

						default:
							if (cnt6 >= 1)
								goto loop6;

							EarlyExitException eee6 = new EarlyExitException( 6, input );
							DebugRecognitionException(eee6);
							throw eee6;
						}
						cnt6++;
					}
					loop6:
						;

					} finally { DebugExitSubRule(6); }

					DebugLocation(74, 20);
					WORD35=(CommonToken)Match(input,WORD,Follow._WORD_in_text709); 
					WORD35_tree = (CommonTree)adaptor.Create(WORD35);
					adaptor.AddChild(root_0, WORD35_tree);

					}
					break;

				default:
					goto loop7;
				}
			}

			loop7:
				;

			} finally { DebugExitSubRule(7); }


			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("text", 8);
			LeaveRule("text", 8);
			LeaveRule_text();
		}
		DebugLocation(75, 6);
		} finally { DebugExitRule(GrammarFileName, "text"); }
		return retval;

	}
	// $ANTLR end "text"

	partial void EnterRule_weight();
	partial void LeaveRule_weight();

	// $ANTLR start "weight"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:77:1: weight : ( FLOAT | NUMBER );
	[GrammarRule("weight")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> weight()
	{
		EnterRule_weight();
		EnterRule("weight", 9);
		TraceIn("weight", 9);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken set36 = default(CommonToken);

		CommonTree set36_tree = default(CommonTree);
		try { DebugEnterRule(GrammarFileName, "weight");
		DebugLocation(77, 20);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:78:7: ( FLOAT | NUMBER )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:
			{
			root_0 = (CommonTree)adaptor.Nil();

			DebugLocation(78, 7);

			set36=(CommonToken)input.LT(1);
			if (input.LA(1)==FLOAT||input.LA(1)==NUMBER)
			{
				input.Consume();
				adaptor.AddChild(root_0, (CommonTree)adaptor.Create(set36));
				state.errorRecovery=false;
			}
			else
			{
				MismatchedSetException mse = new MismatchedSetException(null,input);
				DebugRecognitionException(mse);
				throw mse;
			}


			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("weight", 9);
			LeaveRule("weight", 9);
			LeaveRule_weight();
		}
		DebugLocation(78, 20);
		} finally { DebugExitRule(GrammarFileName, "weight"); }
		return retval;

	}
	// $ANTLR end "weight"

	partial void EnterRule_reps();
	partial void LeaveRule_reps();

	// $ANTLR start "reps"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:80:1: reps : NUMBER ;
	[GrammarRule("reps")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> reps()
	{
		EnterRule_reps();
		EnterRule("reps", 10);
		TraceIn("reps", 10);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken NUMBER37 = default(CommonToken);

		CommonTree NUMBER37_tree = default(CommonTree);
		try { DebugEnterRule(GrammarFileName, "reps");
		DebugLocation(80, 14);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:81:7: ( NUMBER )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:81:9: NUMBER
			{
			root_0 = (CommonTree)adaptor.Nil();

			DebugLocation(81, 9);
			NUMBER37=(CommonToken)Match(input,NUMBER,Follow._NUMBER_in_reps761); 
			NUMBER37_tree = (CommonTree)adaptor.Create(NUMBER37);
			adaptor.AddChild(root_0, NUMBER37_tree);

			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("reps", 10);
			LeaveRule("reps", 10);
			LeaveRule_reps();
		}
		DebugLocation(81, 14);
		} finally { DebugExitRule(GrammarFileName, "reps"); }
		return retval;

	}
	// $ANTLR end "reps"

	partial void EnterRule_sets();
	partial void LeaveRule_sets();

	// $ANTLR start "sets"
	// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:83:1: sets : NUMBER ;
	[GrammarRule("sets")]
	private AstParserRuleReturnScope<CommonTree, CommonToken> sets()
	{
		EnterRule_sets();
		EnterRule("sets", 11);
		TraceIn("sets", 11);
		AstParserRuleReturnScope<CommonTree, CommonToken> retval = new AstParserRuleReturnScope<CommonTree, CommonToken>();
		retval.Start = (CommonToken)input.LT(1);

		CommonTree root_0 = default(CommonTree);

		CommonToken NUMBER38 = default(CommonToken);

		CommonTree NUMBER38_tree = default(CommonTree);
		try { DebugEnterRule(GrammarFileName, "sets");
		DebugLocation(83, 14);
		try
		{
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:84:7: ( NUMBER )
			DebugEnterAlt(1);
			// C:\\Users\\Bacon\\workspaceANTLR\\Text\\src\\kebab\\bacon\\PowerLogGrammar.g:84:9: NUMBER
			{
			root_0 = (CommonTree)adaptor.Nil();

			DebugLocation(84, 9);
			NUMBER38=(CommonToken)Match(input,NUMBER,Follow._NUMBER_in_sets781); 
			NUMBER38_tree = (CommonTree)adaptor.Create(NUMBER38);
			adaptor.AddChild(root_0, NUMBER38_tree);

			}

			retval.Stop = (CommonToken)input.LT(-1);

			retval.Tree = (CommonTree)adaptor.RulePostProcessing(root_0);
			adaptor.SetTokenBoundaries(retval.Tree, retval.Start, retval.Stop);

		}
		catch (RecognitionException re)
		{
			ReportError(re);
			Recover(input,re);
		retval.Tree = (CommonTree)adaptor.ErrorNode(input, retval.Start, input.LT(-1), re);

		}
		finally
		{
			TraceOut("sets", 11);
			LeaveRule("sets", 11);
			LeaveRule_sets();
		}
		DebugLocation(84, 14);
		} finally { DebugExitRule(GrammarFileName, "sets"); }
		return retval;

	}
	// $ANTLR end "sets"
	#endregion Rules


	#region DFA
	private DFA7 dfa7;

	protected override void InitDFAs()
	{
		base.InitDFAs();
		dfa7 = new DFA7( this );
	}

	private class DFA7 : DFA
	{
		private const string DFA7_eotS =
			"\x4\xFFFF";
		private const string DFA7_eofS =
			"\x4\xFFFF";
		private const string DFA7_minS =
			"\x1\x1B\x1\x9\x2\xFFFF";
		private const string DFA7_maxS =
			"\x1\x1E\x1\x1B\x2\xFFFF";
		private const string DFA7_acceptS =
			"\x2\xFFFF\x1\x2\x1\x1";
		private const string DFA7_specialS =
			"\x4\xFFFF}>";
		private static readonly string[] DFA7_transitionS =
			{
				"\x1\x1\x2\xFFFF\x1\x2",
				"\x1\x2\x8\xFFFF\x1\x2\x7\xFFFF\x1\x3\x1\x1",
				"",
				""
			};

		private static readonly short[] DFA7_eot = DFA.UnpackEncodedString(DFA7_eotS);
		private static readonly short[] DFA7_eof = DFA.UnpackEncodedString(DFA7_eofS);
		private static readonly char[] DFA7_min = DFA.UnpackEncodedStringToUnsignedChars(DFA7_minS);
		private static readonly char[] DFA7_max = DFA.UnpackEncodedStringToUnsignedChars(DFA7_maxS);
		private static readonly short[] DFA7_accept = DFA.UnpackEncodedString(DFA7_acceptS);
		private static readonly short[] DFA7_special = DFA.UnpackEncodedString(DFA7_specialS);
		private static readonly short[][] DFA7_transition;

		static DFA7()
		{
			int numStates = DFA7_transitionS.Length;
			DFA7_transition = new short[numStates][];
			for ( int i=0; i < numStates; i++ )
			{
				DFA7_transition[i] = DFA.UnpackEncodedString(DFA7_transitionS[i]);
			}
		}

		public DFA7( BaseRecognizer recognizer )
		{
			this.recognizer = recognizer;
			this.decisionNumber = 7;
			this.eot = DFA7_eot;
			this.eof = DFA7_eof;
			this.min = DFA7_min;
			this.max = DFA7_max;
			this.accept = DFA7_accept;
			this.special = DFA7_special;
			this.transition = DFA7_transition;
		}

		public override string Description { get { return "()* loopback of 74:14: ( ( WS !)+ WORD )*"; } }

		public override void Error(NoViableAltException nvae)
		{
			DebugRecognitionException(nvae);
		}
	}


	#endregion DFA

	#region Follow sets
	private static class Follow
	{
		public static readonly BitSet _exercise_in_evaluate196 = new BitSet(new ulong[]{0x100000000UL});
		public static readonly BitSet _32_in_evaluate199 = new BitSet(new ulong[]{0x4000000UL});
		public static readonly BitSet _exercise_in_evaluate201 = new BitSet(new ulong[]{0x100000000UL});
		public static readonly BitSet _EOF_in_evaluate205 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _set_in_annotatedSet239 = new BitSet(new ulong[]{0x80000002UL});
		public static readonly BitSet _forced_in_annotatedSet242 = new BitSet(new ulong[]{0x80000002UL});
		public static readonly BitSet _note_in_annotatedSet244 = new BitSet(new ulong[]{0x80000002UL});
		public static readonly BitSet _flag_in_annotatedSet246 = new BitSet(new ulong[]{0x80000002UL});
		public static readonly BitSet _sets_in_set307 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _X_in_set309 = new BitSet(new ulong[]{0x40000UL});
		public static readonly BitSet _reps_in_set311 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _X_in_set313 = new BitSet(new ulong[]{0x40200UL});
		public static readonly BitSet _weight_in_set315 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _reps_in_set361 = new BitSet(new ulong[]{0x10000000UL});
		public static readonly BitSet _X_in_set363 = new BitSet(new ulong[]{0x40200UL});
		public static readonly BitSet _weight_in_set365 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _weight_in_set412 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _text_in_exercise477 = new BitSet(new ulong[]{0x8000000UL});
		public static readonly BitSet _WS_in_exercise480 = new BitSet(new ulong[]{0x8040200UL});
		public static readonly BitSet _annotatedSet_in_exercise483 = new BitSet(new ulong[]{0x8000002UL});
		public static readonly BitSet _31_in_flag540 = new BitSet(new ulong[]{0x1005000UL});
		public static readonly BitSet _set_in_flag543 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _31_in_note578 = new BitSet(new ulong[]{0x20000UL});
		public static readonly BitSet _NOTE_in_note580 = new BitSet(new ulong[]{0x20000000UL});
		public static readonly BitSet _29_in_note582 = new BitSet(new ulong[]{0x4000000UL});
		public static readonly BitSet _text_in_note584 = new BitSet(new ulong[]{0x40000000UL});
		public static readonly BitSet _30_in_note586 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _31_in_forced639 = new BitSet(new ulong[]{0x800UL});
		public static readonly BitSet _FR_in_forced641 = new BitSet(new ulong[]{0x20000000UL});
		public static readonly BitSet _29_in_forced643 = new BitSet(new ulong[]{0x40000UL});
		public static readonly BitSet _reps_in_forced645 = new BitSet(new ulong[]{0x40000000UL});
		public static readonly BitSet _30_in_forced647 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _WORD_in_text702 = new BitSet(new ulong[]{0x8000002UL});
		public static readonly BitSet _WS_in_text705 = new BitSet(new ulong[]{0xC000000UL});
		public static readonly BitSet _WORD_in_text709 = new BitSet(new ulong[]{0x8000002UL});
		public static readonly BitSet _NUMBER_in_reps761 = new BitSet(new ulong[]{0x2UL});
		public static readonly BitSet _NUMBER_in_sets781 = new BitSet(new ulong[]{0x2UL});
	}
	#endregion Follow sets
}
