// <auto-generated />
namespace PowerLog.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class InitialState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialState));
        
        string IMigrationMetadata.Id
        {
            get { return "201209212032179_InitialState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
